# Generated by Django 3.2.6 on 2021-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0002_auto_20210812_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_types',
            field=models.CharField(blank=True, choices=[(6, 'Phone number'), (bool, 'Job'), (str, 'Company name'), (str, 'Domain name')], max_length=1, verbose_name='тип данных'),
        ),
    ]
