# Generated by Django 3.2.6 on 2021-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0003_column_data_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_types',
            field=models.CharField(blank=True, choices=[(int, 'Phone number'), (bool, 'Job'), (str, 'Company name'), (str, 'Domain name')], max_length=1, verbose_name='тип данных'),
        ),
    ]
