# Generated by Django 3.2.6 on 2021-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0004_alter_column_data_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_types',
            field=models.CharField(blank=True, choices=[(23, 'Phone number'), (bool, 'Job'), ('', 'Company name'), ('', 'Domain name')], max_length=1, verbose_name='тип данных'),
        ),
    ]
