# Generated by Django 3.2.6 on 2021-08-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0005_alter_column_data_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='data_types',
        ),
    ]
