# Generated by Django 3.2.6 on 2021-09-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0006_remove_column_data_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelschema',
            options={'ordering': ('-time_to_create',), 'verbose_name': 'схема', 'verbose_name_plural': 'схемы'},
        ),
        migrations.AddField(
            model_name='modelschema',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PRD', 'обрабатывается'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='time_to_update',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлена'),
        ),
        migrations.AlterField(
            model_name='column',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemachilds', to='dataschems.modelschema'),
        ),
        migrations.AlterField(
            model_name='modelschema',
            name='time_to_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создана'),
        ),
        migrations.AlterField(
            model_name='modelschema',
            name='title',
            field=models.CharField(max_length=64, verbose_name='имя схемы'),
        ),
    ]
