# Generated by Django 3.2.6 on 2021-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0007_auto_20210908_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='description',
        ),
        migrations.AddField(
            model_name='column',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество'),
        ),
    ]
