# Generated by Django 3.2.6 on 2021-09-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0009_auto_20210908_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='model',
            new_name='model_schema',
        ),
    ]
