# Generated by Django 3.2.6 on 2021-09-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataschems', '0010_rename_model_column_model_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='model_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemachilds', to='dataschems.modelschema', verbose_name='схема'),
        ),
        migrations.AlterField(
            model_name='modelschema',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель схемы'),
        ),
    ]
