# Generated by Django 3.2.6 on 2021-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0011_auto_20210908_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'столбец схемы', 'verbose_name_plural': 'столбцы схемы'},
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Имя столбца'),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('FN', 'Full name'), ('INT', 'Integer'), ('CNM', 'Company'), ('JT', 'Job')], default=None, max_length=3, verbose_name='тип'),
        ),
    ]
