# Generated by Django 3.2.6 on 2021-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataschems', '0012_auto_20210909_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('FN', 'Full name'), ('INT', 'Integer'), ('CNM', 'Company'), ('JT', 'Job'), ('PN', 'phone number')], default=None, max_length=3, verbose_name='тип'),
        ),
    ]
